data_builder: DataBuilderSFSinglePrompt
instruction: "Extraer informaci√≥n relevante del enunciado del usuario, dadas las siguientes etiquetas y descripciones de ranuras:\n{{{slot_dict}}}\n"
prompt: "---\nUsuario: \"{utterance}\"\nInfo:"